version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=1qaz@WSX"
      - "MYSQL_DATABASE=senaoapi"
  api:
    # build: .
    image: dylanhuang399/apiassignment
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    depends_on:
      - db
      - redis
    links:
      - "db:database"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

